NewStory/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import lab_9.urls as lab_9
import lab_8.urls as lab_8
import lab_5.urls as lab_5
# from lab_1.views import index as index_lab1
#from lab_4.views import mainHome as home



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(lab_5,namespace='lab_5')),
    url(r'^lab_8/', include(lab_8,namespace='lab_8')),
    url(r'^lab_9/', include(lab_9,namespace='lab_9')),
    url(r'^auth/', include('social_django.urls', namespace='social')),
]

lab_5/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views
app_name = 'lab_4'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.mainHome, name="mainHome"),
    path('profil/', views.profile, name="myProfile"),
    path('register/', views.register, name="registerHere"),

    path('add_schedule/', views.schedule_form, name="addSchedule"),
    path('schedule_list/', views.schedule_list, name="scheduleList"),
    path('display/', views.display_form, name="display"), 
    path('schedule_remove/', views.remove_schedule, name="schedule_remove"),

    path('email_validation/', views.email_validation, name="email_validation"),
    path('subscribeform/', views.register_form, name="display_subscribeform"),
    path('subscribe_list/', views.register_list, name="subscribe_list"),

    path('unsubscribe/', views.unsubscribe, name="unsubscribe"),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lab_5/models.py
from django.db import models
from django.utils import timezone
from datetime import date, datetime

class Schedule(models.Model):
	day = models.CharField(max_length=27)
	date = models.DateTimeField()
	hour_min = models.TimeField(auto_now = False, auto_now_add = False)
	activity = models.CharField(max_length=27)
	place = models.CharField(max_length=27)
	category = models.CharField(max_length=27)

class Register(models.Model):
	name = models.CharField(max_length=30)
	email = models.EmailField(max_length=40, unique=True)
	password = models.CharField(max_length=20)

lab_5/forms.py
from django import forms
import datetime

class ScheduleForm(forms.Form):
	day = forms.CharField(label="Day")
	date = forms.DateTimeField(label="Date",widget = forms.DateInput(attrs = {'type' : 'date'}))
	hour_min = forms.TimeField(label="Hour : Min", widget = forms.TimeInput(attrs={'type' : 'time'}))
	activity = forms.CharField(label="Activity")
	place = forms.CharField(label="Location")
	category = forms.CharField(label="Category")

class RegisterForm(forms.Form):
	name = forms.CharField(label="Name", required=True, widget=forms.TextInput(attrs={'id' : 'subscriberName'}))
	email = forms.EmailField(label="Email", required=True, widget=forms.TextInput(attrs={'id' : 'subscriberEmail'}))
	password = forms.CharField(label="Password", required=True, min_length=8, max_length=15,
								 widget=forms.PasswordInput(attrs={'id' : 'subscriberPass'}))


	

lab_5/views.py
from django.shortcuts import render, redirect
from .forms import ScheduleForm, RegisterForm
from .models import Schedule, Register
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.views.decorators.csrf import csrf_exempt

from django.core.validators import validate_email
from django.core.exceptions import ValidationError
import json


def mainHome(request):
 	return render(request,'pepew3.html')

def profile(request):
	return render(request, 'pepew3_2.html')

def register(request):
	response = {}
	response['registrasi'] = RegisterForm 
	return render(request, 'pepew3_3.html', response)


def register_form(request):
	response = {}
	form = RegisterForm(request.POST or None)
	if(request.method == "POST" and form.is_valid()):
		name = request.POST.get('name')
		email = request.POST.get('email')
		password = request.POST.get('password')

		Register.objects.create(name=name, email=email, password=password)
		return JsonResponse({'result' : 'Thanks ' + name + ' for subscribe me!!!'})

	else:
		return JsonResponse({'result' : 'fail'})


def email_validation(request):
	try:
		validate_email(request.POST.get('email'))
	except:
		return JsonResponse({
			'message':'Email format is invalid!',
			'status':'fail'
		})

	exist = Register.objects.filter(email=request.POST['email'])

	if exist:
		return JsonResponse({
			'message':'Email already exists!',
			'status':'fail'
		})

	return JsonResponse({
		'message':'Email now valid',
		'status':'success'
	})


def schedule_form(request):
	response = {}
	response['form'] = ScheduleForm
	return render(request, "ScheduleForm.html", response)


def display_form(request):	
	response = {}
	form = ScheduleForm(request.POST or None)
	if(request.method == "POST" and form.is_valid()):
		response['day'] = request.POST.get('day')
		response['date'] = request.POST.get('date')
		response['hour_min'] = request.POST.get('hour_min')
		response['activity'] = request.POST.get('activity')
		response['place'] = request.POST.get('place')
		response['category'] = request.POST.get('category')

		Schedules = Schedule(day=response['day'], date=response['date'], hour_min=response['hour_min'],
		 					 activity=response['activity'], place=response['place'], category=response['category'])

		
		Schedules.save()

		response['form'] = form

		Schedules = Schedule.objects.all()
		response['Schedules'] = Schedules
		return render(request, 'ScheduleList.html' , response)
	
	else:
		return HttpResponseRedirect('/')

def schedule_list(request):
	response = {}
	Schedules = Schedule.objects.all()
	response['Schedules'] = Schedules
	return render(request, 'ScheduleList.html' , response)

def remove_schedule(request):
	Schedules = Schedule.objects.all().delete()
	return render(request, 'ScheduleList.html', {})

def register_list(request):
	response = []
	# count = 1;
	register = Register.objects.all()
	for i in register:
		response.append({'name':i.name, 'email':i.email, 'pass':i.password})
		# count += 1

	data = response[::-1]
	return JsonResponse({
		'dataa' : data
 		})

def unsubscribe(request):
	email = request.GET['email']
	email = email[1:-1]
	Register.objects.filter(email= email).delete()

	response = []
	# count = 1;
	register = Register.objects.all()
	for i in register:
		response.append({'name':i.name, 'email':i.email, 'pass':i.password})
		# count += 1

	data = response[::-1]
	return JsonResponse({
		'dataa' : data
 		})

lab_5/templates/ScheduleForm.html
{% extends 'starter.html' %}


{% block content %}
{% load static %}

<div style="text-align: center">
	<br>
	<h1><strong class="judulDiv">Create Schedule Here </strong></h1>
		<section>
			<div class = "my-auto">
				<div>
					<form id='form' method="POST" action="{% url 'lab_4:display' %}" >
						{% csrf_token %}
						{% for field in form %}
						<div class = "form-group">
							<strong><label class = "text"> {{ field.label }} </label><br> {{field}}
							</label>
						</div>
						{% endfor %}
						<input id="submit" type="submit" class="btn btn-lg btn-primary" value="Create"><br>
					</form>
				</div>
			</div>
		</section>
</div>
{% endblock %}

lab_5/templates/ScheduleList.html
{% extends 'starter.html' %}



{% block content %}
{% load static %}
<div style="background-color:#FFD089; text-align: center;height: 45vw">
	<br> 
	<h1><strong class="judulDiv">List of Schedule </strong></h1>
	<div style="margin:4vw">
		<table class="table text">
			{% if Schedules %}
				<thead style="background-color:#3f2a14; color:#FFFFFF;">
					<th>Date</th>
					<th>Hour</th>
					<th>Activity</th>
					<th>Location</th>
					<th>Category</th>
				</thead>

				<tbody id="customers">
					{% for s in Schedules %}
						<tr class = "success">
							<td>{{s.day}} , {{s.date}}</td>
							<td>{{s.hour_min}}</td>
							<td>{{s.activity}}</td>
							<td>{{s.place}}</td>
							<td>{{s.category}}</td>
						</tr>
					{% endfor %}
				</tbody>

			{% else %}
				<h2 class = "text">### Empty ###</h2>
			{% endif %}
		</table>
	</div>
	<button type="button" class="btn btn-danger" onclick="location.href='{% url 'lab_4:schedule_remove' %}' "> Remove Schedule</button>

</div>

{% endblock %}

lab_5/templates/pepew3.html
{% extends 'starter.html' %}

{% block content %}
{% load static %}

	<div class = "foto">
		<article><br></article>
		<div id = "textBoxFoto">
			<article class="text" style="font-size:3.2vw;margin-left:8vw;color:#683B12">
				A Journey<br>From Someone<br><br>&emsp;&emsp;Whose Life<br>&emsp;&emsp;In The Middle Of<br>&emsp;&emsp;The Universe
			</article>
		</div>
		<br><br><br><br>
	</div>
	<hr class = "garis">


	<div class = "bot-nav">
		<div class="text bot-nav1"> 
			<article>
				<center>
					<strong style="font-size:2vw">
						Hai, I’m Yama
					</strong>
					<br>I’m a Programmer whose love art, perfectionist, and you<br><a href="profil/" class="btn btn-primary btn-sm active" role="button" aria-pressed="true" style="margin:1vw;box-shadow:2px 2px 2px grey;font-size:1.2vw">Learn more</a>
				</center>
			</article>
		</div>

		<div class="text bot-nav2"> 
			<article>
				<center>
					<strong style="font-size:2vw">
						Multi Discipline
					</strong>
					<br>Beside coding, there are organitation, art, and sport too<br><a href="profil/" class="btn btn-primary btn-sm active" role="button" aria-pressed="true" style="margin:1vw;box-shadow:2px 2px 2px grey;font-size:1.2vw">Learn more</a>
				</center>
			</article>
		</div>

		<div class="text bot-nav3"> 
			<article>
				<center>
					<strong style="font-size:2vw">
						Explorer
					</strong>
					<br>our world is very-very big, but these are my interest<br><a href="profil/" class="btn btn-primary btn-sm active" role="button" aria-pressed="true" style="margin:1vw;box-shadow:2px 2px 2px grey;font-size:1.2vw">Learn more</a>
				</center>
			</article>
		</div>

		<div class="text bot-nav4"> 
			<article>
				<center>
					<strong style="font-size:2vw">
						Interested?
					</strong>
					<br>Wanna know more? what you waiting for? Got in touch!<br><a href="register/" class="btn btn-primary btn-sm active" role="button" aria-pressed="true" style="margin:1vw;box-shadow:2px 2px 2px grey;font-size:1.2vw">Learn more</a>
				</center>
			</article>
		</div>
	</div>
{% endblock %}

lab_5/templates/pepew3_2.html
{% extends 'starter.html' %}

{% block content %}
{% load static %}

	<div style="background-color:#FFD089">
		<img src="https://i.imgur.com/Ezf084I.jpg" alt="foto uci" class="logo" style="width:20vw;border-radius: 50%;margin:3vw;margin-top:1.6vw;">
		<center>
			<article class="text" style="margin-left:29vw;margin-right:10vw;"><br>
				<strong class="judulDiv">
					This is Me
				</strong><br><br>
				<article style="font-size:2vw;">
					Hai, I’m Yama
				</article>
				<article style="font-size:1.5vw;">
					Currently a computer science student undergraduate in University of Indonesia. Perfectionist and ambitious are two things that are very attached to me. I spent my spare time for refreshing my soul, such as playing games, sport, or watch some film.<br><br><br>
				</article>
			</article>
		</center>
	</div><hr class = "garis">

	<div class="skills">
		<br><center>
			<strong class="judulDiv">
				My Skills
			</strong>
		</center>

		<div class="text program"> 
			<center>
				<article>
					&emsp;<img src="https://www.shareicon.net/data/512x512/2016/01/13/702849_code_512x512.png" alt="code"style="width:8vw;"><br>&emsp;
					<strong style="font-size:1.8vw">
						Programming
					</strong> 
					<br>&emsp;C++<br>&emsp;Python<br>&emsp;Java<br>
				</article>
			</center>
		</div>

		<div class="text sport"> 
			<center>
				<article>
					<strong style="font-size:1.8vw">
						Sport
					</strong>
					<br>Badminton<br>Taekwondo<br>E-Sport<br>
					<img src="https://mbtskoudsalg.com/images/shoe-silhouette-png-8.png" alt="sport shoes" style="width:10vw;margin-top:2vw;">
				</article>
			</center>
		</div>

		<div class="text organitation"> 
			<center>
				<article>
					<img src="https://mbtskoudsalg.com/images/png-background-creator.png" style="width:8vw;">
					<strong style="font-size:1.8vw">
						Organitation
					</strong>
					<br>DPM Fasilkom UI<br>Ristek Fasilkom UI<br>A Lot of Events<br>
				</article>
			</center>
		</div>

		<div class="text editing"> 
			<center>
				<article>
					<strong style="font-size:1.8vw">
						Editing
					</strong>
					<br>Photoshop<br>Sony Vegas<br>
				<img src="https://vignette.wikia.nocookie.net/lostpedia/images/e/e0/Clapperboard.png/revision/latest?cb=20080328214142" style="width:7.5vw;margin-top:1.5vw;">
			</article>
		</center>
		</div>

		<div class="text character"> 
			<center>
				<article>
					<img src="https://www.freeiconspng.com/uploads/muscle-icon-1.png" style="width:10vw;">
					<strong style="font-size:1.8vw">
						Character
					</strong>
					<br>Ambitious<br>Adaptive<br>
				</article>
			</center>
		</div>
	</div>
	<hr class = "garis">


	<div style="background-color:#FFEEB1;height:39vw;">
		<br><center>
			<strong class="judulDiv">
				Interest in
			</strong>
		</center>

		<div class="text" style="float:left;font-size:1.8vw;margin:1.2vw;margin-top:0vw;margin-left:5vw;width:45vw;text-align: right;">
			<strong style="font-size:3vw;color:#905050;">
				<u text-align: right;>Formal</u>&ensp;
			</strong>
			<article style="margin:1vw; margin-left:0vw;">
				<strong style="font-size:2vw;">
					Problem Solve
				</strong>
				<br>I’d like to solve a problem that people can’t </br>
			</article>

			<article style="margin:1vw;">
				<strong style="font-size:2vw; margin-left:0vw;">
				UI/UX Designer
				</strong>
				<br>Study PPW in University of Indonesia, make me want to be a UI/UX Designer</br>
			</article> 
				
			<article style="margin:1vw; margin-left:0vw;">	
				<strong style="font-size:2vw;">
					Game Development
				</strong>
				<br>beside like to play e-sport, I also like to make it</br>
			</article>
		</div>

		<div class="text" style="float:left;font-size:1.8vw;margin:1.2vw;margin-top:0vw;width:45vw;text-align: left;">
			<strong style="font-size:3vw;color:#905050;">
				<u text-align: right;>Informal</u>
			</strong>
			<article style="margin:1vw; margin-left:0vw;">
				<strong style="font-size:2vw;">
					E-Sport
				</strong>
				<br>Playing game is the best refresing for me</br>
			</article>

			<article style="margin:1vw;">
				<strong style="font-size:2vw; margin-left:0vw;">
				Discover the Whole World
				</strong>
				<br>Our world absolutly big, but nothing is immposible until God call you to come back home</br>
			</article> 
				
			<article style="margin:1vw; margin-left:0vw;">	
				<strong style="font-size:2vw;">
					Nature and Ecosystem
				</strong>
				<br>Tree, bird, sea sore, mountain, and me...</br>
			</article>

		</div>
	</div>
	<hr class = "garis">

	<div style="background-color:#D56509;height:15vw;">
		<br><center>
			<strong class="judulDiv" style="font-size:3vw;line-height:3vw;">
				Find Me
			</strong>
		</center>
		<article>
			<img src="http://pngimg.com/uploads/email/email_PNG55.png" alt="email" style="width:3.5vw; margin-left:9.5vw;margin-top:3vw;">
			gustingurah.yama@gmail.com
			<img src="https://image.ibb.co/dnJjEz/line.png" alt="line" style="width:3.5vw; margin-left:5vw;margin-top:3vw;">
			@gnyap2310
			<img src="https://image.ibb.co/d4aaMe/ig.png" alt="ig" style="width:3.5vw; margin-left:5vw;margin-top:3vw;">
			@gustinyap
			<img src="https://preview.ibb.co/gHFxZz/phone.png" alt="phone" style="width:3.5vw; margin-left:5vw;margin-top:3vw;">
			083838718942
		</article>
	</div> 
{% endblock %}

lab_5/templates/pepew3_3.html
{% extends 'starter.html' %}

{% block content %}
{% load static %}


<div style="text-align: center">
	<br>
	<h1><strong class="judulDiv"> Subscribe Here!! </strong></h1>
		<section>
			<div class = "my-auto">
				<div>
					<form id='form' method="POST" >
						{% csrf_token %}
						{% for field in registrasi %}
						<div class = "form-group">
							<strong><label class = "text"> {{ field.label }} </label><br> {{field}}
							</label>
						</div>
						{% endfor %}
						<input id="subscribe" type="submit" class="btn btn-lg btn-primary" value="Subscribe!"><br>
					</form>

				<div id="subscribeStatus"></div>
				</div>
			</div>
		</section>
</div>
<br>
<div style="margin:3vw">
	<table id="customers" class="table table-striped table-bordered table-sm text" cellspacing="0" width="100%">
		<thead class="thead-dark">
			<tr>
				<th class="th-sm">Name</th>
				<th class="th-sm">Email</th>
				<!--       
				<th class="th-sm">Publisher
				<i class="fa fa-sort float-right" aria-hidden="true"></i>
				</th> -->
				<th class="th-sm">Unsubscribe</th>
			</tr>
		</thead>
		<tbody id="boddy">
				<tr>
					<td></td>
					<td></td>
					<td></td>
				</tr>
		</tbody>
	</table>
</div>

<!-- 	<div id="registerBack">
		<article style="margin-left:36vw;padding-top:2.5vw;"><strong class="judulDiv">Register Here</strong></article>
		<form style="margin-left:5vw;margin-right:5vw;">
			<div class="form-group">
		    	<label for="name" class="text">Name</label>
		    	<input type="text" class="form-control" id="name" aria-describedby="nameHelp" placeholder="Enter Name">
		 	</div>
		 	<div class="form-group">
		    	<label for="bornDate" class="text">Born Date</label>
		    	<input type="date" class="form-control" id="bornDate" aria-describedby="dateHelp" placeholder="Enter Date">
		 	</div>
		 	<div class="form-group">
		    	<label for="email" class="text">Email Address</label>
		    	<input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
		    	<small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
		    </div>
		 	<div class="form-group">
		    	<label for="username" class="text">Username</label>
		    	<input type="text" class="form-control" id="username" placeholder="Enter Username">
		  	</div>
		  	<div class="form-group">
					<label for="Password" class="text">Password</label>
					<input type="password" class="form-control" id="Password" placeholder="Password">
				</div>
				<div class="form-group">
					<label for="PasswordConf" class="text">Password Confirmation</label>
					<input type="password" class="form-control" id="PasswordConf" placeholder="Password">
				</div>
				<a href="javascript:history.go(-1);" class="btn btn-primary btn-sm active" role="button" aria-pressed="true" style="box-shadow:2px 2px 2px grey;font-size:1.5vw;">Submit</a>
		</form>
	</div> -->
{% endblock %}

lab_5/templates/starter.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
	<title>My Journey</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static "css/pepew3.css" %}">
	<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Suravaram" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Habibi" rel="stylesheet">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
 
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
	<script src="{%static "js/lab10.js" %}"></script>

</head>

<body style="background-color:#FFD089;">
	<div class="head">
		<img src="https://i.imgur.com/RSU6Ba8.jpg" alt="logo" class="logo">
		<article class="judulHeader">
			FRAMTIDEN
		</article>
		<article class="subJudulHeader">
			Gusti Ngurah Yama Adi Putra's Journey
		</article>
	</div>
	<hr class = "garis">

	<!-- NAVBAR -->
	<nav class="navbar navbar-expand-lg navbar-light">
		<a class="navbar-brand active" href="{% url 'lab_4:mainHome' %}"> <img src="https://vignette.wikia.nocookie.net/lionheart-tactics/images/9/9a/Home.png/revision/latest?cb=20150218040604&format=original" style="width:3vw;"><span class="sr-only">(current)</span></a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		  	<span class="navbar-toggler-icon"></span>
		</button>
	  
		<div class="collapse navbar-collapse" id="navbarSupportedContent">
		  	<ul class="navbar-nav mr-auto">
				<li class="nav-item">
			  		<a class="nav-link" href="{% url 'lab_4:myProfile' %}">Profile</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'lab_4:registerHere' %}">Register</a>
			  	</li>
			  	<li class="nav-item">
					<a class="nav-link" href="{% url 'lab_4:addSchedule' %}">Add Schedule</a>
			  	</li>
			  	<li class="nav-item">
					<a class="nav-link" href="{% url 'lab_4:scheduleList' %}">My Schedule</a>
			  	</li>
		  	</ul>
		</div>
	</nav>
	{% block content %}
	{% endblock %}

</body>
</html>