NewStory/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import lab_9.urls as lab_9
import lab_8.urls as lab_8
import lab_5.urls as lab_5
# from lab_1.views import index as index_lab1
#from lab_4.views import mainHome as home



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(lab_5,namespace='lab_5')),
    url(r'^lab_8/', include(lab_8,namespace='lab_8')),
    url(r'^lab_9/', include(lab_9,namespace='lab_9')),
    url(r'^auth/', include('social_django.urls', namespace='social')),
]

lab_5/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views
app_name = 'lab_4'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.mainHome, name="mainHome"),
    path('profil/', views.profile, name="myProfile"),
    path('register/', views.register, name="registerHere"),

    path('add_schedule/', views.schedule_form, name="addSchedule"),
    path('schedule_list/', views.schedule_list, name="scheduleList"),
    path('display/', views.display_form, name="display"), 
    path('schedule_remove/', views.remove_schedule, name="schedule_remove"),

    path('email_validation/', views.email_validation, name="email_validation"),
    path('subscribeform/', views.register_form, name="display_subscribeform"),
    path('subscribe_list/', views.register_list, name="subscribe_list"),

    path('unsubscribe/', views.unsubscribe, name="unsubscribe"),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lab_8/urls.py
from django.conf.urls import url
from .views import makeStatus, remove_list

app_name = "lab_8"
urlpatterns = [
	url(r'^$', makeStatus, name='homepage'),
	url(r'home/', makeStatus, name='home'),
	url(r'remove/', remove_list, name="remove"),
]

lab_8/models.py
from django.db import models

class Status(models.Model):
	status = models.CharField(max_length=300)
	when = models.DateTimeField(auto_now_add=True, editable=False, null=False, blank=False) #ambil jam sekarang

lab_8/forms.py
from django import forms
from .models import Status

class statusForm(forms.Form):
	status = forms.CharField(label="", max_length = 300, widget=forms.TextInput(attrs={'placeholder': "Bagaimana Harimu?"}))

lab_8/views.py
from django.shortcuts import render, redirect
from .forms import statusForm
from .models import Status
from django.http import HttpResponseRedirect

response = {}

def makeStatus(request):
	form = statusForm(request.POST or None)	
	if(request.method == "POST" and form.is_valid()):
		status = request.POST.get('status')

		Status.objects.create(status=status)
		return redirect("lab_8:homepage")
	# else:
	# 	return HttpResponseRedirect('/')


	Statuses = Status.objects.all().order_by("-id")
	response = {
		"Statuses" : Statuses,
		"form" : form,

	}
	return render(request, 'landing_page.html' , response)

def remove_list(request):
	Statuses = Status.objects.all().delete()
	return render(request, 'landing_page.html', {})

lab_8/templates/landing_page.html
{% load static %}
<!DOCTYPE html>
<html>

	<head>
		<title>TDD-D</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="{% static "css/style.css" %}">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		<script src="http://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.2/modernizr.js"></script>
		<script src="{% static 'js/themeNacordion.js' %}"></script>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
		<link href="https://fonts.googleapis.com/css?family=Habibi" rel="stylesheet">
	</head>
	<body>
		<div class="se-pre-con"></div>
		<div class="container h-100">
			<div class="row h-100 justify-content-center align-items-center">
				<div class="col-sm-4">
					<dl class="accordion text">
						<dt><a href="">&nbsp;My Info</a></dt>
						<dd>
							Hai, I’m Yama <br>
							Currently a computer science student undergraduate in University of Indonesia. Perfectionist and ambitious are two things that are very attached to me. I spent my spare time for refreshing my soul, such as playing games, sport, or watch some film.
						</dd>

						<dt><a href="">&nbsp;Skill</a></dt>
						<dd name="hide">
							<ul>
							  <li>Programmer (Python, Java, C++, html, CSS, etc)</li>
							  <li>Sport (Badminton, Taekwondo, E-Sport</li>
							  <li>Organitation (DPM Fasilkom UI, Ristek Fasilkom UI ,etc)</li>
							  <li>Editing (Photoshop, Sony Vegas, etc)</li>
							</ul>
						</dd>
						
						<dt><a href="">&nbsp;Achivement</a></dt>
						<dd name="hide">
							<ul>
								<li>Finalis Competitive Programming Vocompfest UGM 2018</li>
								<li>Finalis ACM ICPC Maranatha 2018</li>
								<li>Finalis INC ICPC regional Jakarta 2018</li>
							</ul>
						</dd>

					</dl>
				</div>
				<div class="col-sm-8">
					<div class ="text" style="text-align: center">
						<h1><strong> Hello Apa Kabar? </strong></h1>
						<div class = "my-auto">
							<div>
								<form action="{% url 'lab_8:homepage' %}" id='form' method="POST" >
									{% csrf_token %}
									{{ form }}
									<input id="submit" type="submit" class="btn btn-sm btn-primary bagikan" value="Bagikan"><br>
								</form>
							</div>
						</div>
					</div>
					<center>
						<button type="button" class="btn btn-sm btn-dark" name="change_dark" onclick= dark()>Dark Theme</button>
						<!-- <button type="button" class="btn btn-sm btn-dark" name="organisasi" onclick= "">Add JSON</button> -->
					</center>
				</div>

					<center>
						<div class = 'text'>
							<h3> Daftar Kenangan </h3>
							<table id="customers" class='tabel'>
				                {% if Statuses %}
				                    {% for stat in Statuses %}
				                        <tr>
				                            <td style="width: 70%">{{ stat.status }}</td>
				                            <td style="text-align: right;">{{ stat.when }}</td>
				                        </tr>
				                    {% endfor %}
				                {% else %}
				                    <p>Anda tidak memiliki kenangan...</p> 
				                {% endif %}
				            </table>
				            <button type="button" class="btn btn-danger" name="delete" onclick="location.href='{% url 'lab_8:remove' %}' "> Hapus Kenangan :)</button><br><br><br>
						</div>	
					</center>	
				
			</div>
		</div>
	</body>

</html>

lab_8/templates/profile.html
<!DOCTYPE html>
<!DOCTYPE html>
<html>
	<head>
		<title>About Me</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
		<link href="https://fonts.googleapis.com/css?family=Habibi" rel="stylesheet">
	</head>

	<body style="background-color: #ffd7a0; font-family: 'Habibi', serif;"> <center>
		<button type="button" style = "float: left; margin-left:1vw"class="btn btn-light" onclick="location.href='{% url 'lab_6:home' %}' ">Kembali</button>
		<strong><h1 style="margin: 2vw; margin-right:8vw "> My Info </h1>
	    <h2>
	    	Gusti Ngurah Yama Adi Putra<article style="font-size: 50%;">1706979253</article><hr>
	    </h2></strong>
	    <img src ="http://www.about.tarung2017.com/foto/312.jpg" alt="orang ganteng", height=300>
	    <article>
	    	Study at University of Indonesia
	    	</br> seorang dengan hobi Ngoding <br></br> Seorang mahasiswa yang berharap bisa lulus dengan predikat cumlaude dan berguna bagi sesama. </br>
		</article>
	</center>
	</body>
</html>