NewStory/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import lab_9.urls as lab_9
import lab_8.urls as lab_8
import lab_5.urls as lab_5
# from lab_1.views import index as index_lab1
#from lab_4.views import mainHome as home



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(lab_5,namespace='lab_5')),
    url(r'^lab_8/', include(lab_8,namespace='lab_8')),
    url(r'^lab_9/', include(lab_9,namespace='lab_9')),
    url(r'^auth/', include('social_django.urls', namespace='social')),
]

lab_5/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views
app_name = 'lab_4'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.mainHome, name="mainHome"),
    path('profil/', views.profile, name="myProfile"),
    path('register/', views.register, name="registerHere"),

    path('add_schedule/', views.schedule_form, name="addSchedule"),
    path('schedule_list/', views.schedule_list, name="scheduleList"),
    path('display/', views.display_form, name="display"), 
    path('schedule_remove/', views.remove_schedule, name="schedule_remove"),

    path('email_validation/', views.email_validation, name="email_validation"),
    path('subscribeform/', views.register_form, name="display_subscribeform"),
    path('subscribe_list/', views.register_list, name="subscribe_list"),

    path('unsubscribe/', views.unsubscribe, name="unsubscribe"),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lab_9/urls.py
from django.conf.urls import url
from .views import *

app_name = "lab_9"
urlpatterns = [
	url(r'^$', home, name='homepage'),
	url(r'data/', getData, name='data'),

	url(r'logout/', logout_, name='logout'),

	url(r'fav/', fav, name="favourite"),
    url(r'unfavourite/', unfavourite, name="unfavourite"),
    url(r'get-fav/', get_fav, name="get_favourite"),

]

lab_9/models.py
from django.db import models

lab_9/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
import requests, json
from django.contrib.auth import authenticate, logout
from django.views.decorators.csrf import csrf_exempt
from django.contrib import messages
# from .models import Searching

response = {}
def getData(request):
	search = request.GET.get("search", "quilting")
	URL = "https://www.googleapis.com/books/v1/volumes?q=" + search
	
	getJson = requests.get(URL).json()
	return JsonResponse(getJson)

def home(request):
	if  request.user.is_authenticated and "fav" not in request.session:
		request.session["email"] = request.user.email
		request.session["sessionid"]=request.session.session_key
		request.session["fav"]=[]

	try:
		if request.session["fav"] is not None:
			response["message"] = len(request.session["fav"])
	except:
		response["message"] = 0

	return render(request, 'book.html', response)

@csrf_exempt
def fav(request):
	if(request.method=="POST"):
		lst = request.session["fav"]
		if request.POST["id"] not in lst :
			lst.append(request.POST["id"])

		request.session["fav"]= lst
		response["message"]=len(lst)
		return JsonResponse(response)

	else:
		return HttpResponse("GET Method not allowed")

@csrf_exempt  
def unfavourite(request):
	if(request.method=="POST"):
		lst = request.session["fav"]
		if request.POST["id"] in lst :
			lst.remove(request.POST["id"])

		request.session["fav"]= lst
		response["message"]=len(lst)  

		return JsonResponse(response)

	else:
		return HttpResponse("GET Method not allowed")

@csrf_exempt
def get_fav(request):
	if request.user.is_authenticated :
		if(request.method=="GET"):
			if request.session["fav"] is not None:
				response["message"] = request.session["fav"]
		else:
			response["message"] = "NOT ALLOWED"
	else:
		response["message"] = ""

	return JsonResponse(response)

def logout_(request):
	messages.info(request, "You're Now Logout....")
	logout(request)
	return HttpResponseRedirect('/lab_9')

lab_9/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
	<title>Google Book</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="google-signin-client_id" content="528670758644-9ob4m8f6e90o0hrs2og7o2o2aeij7chr.apps.googleusercontent.com">

	<!-- <script src="http://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.2/modernizr.js"></script> -->

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

	<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Suravaram" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Habibi" rel="stylesheet">
	<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<!-- <link href="css/addons/datatables.min.css" rel="stylesheet"> -->
	<link rel="stylesheet" href="{% static 'css/desain.css' %}">
	<link rel="stylesheet" href="{% static 'css/datatables.min.css' %}">	


	<script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
	<script src="http://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>

</head>

<body>
	<div class="head">
		<img src=" https://scontent.fcgk10-1.fna.fbcdn.net/v/t1.0-9/41984447_2248979878463321_1292254070504947712_n.jpg?_nc_cat=0&oh=9f3e018ad91f8d33c6524fde8e2e0926&oe=5C2CAE40" alt="logo" class="logo">
		<article class="judulHeader">
			FRAMTIDEN
		</article>
		<article class="subJudulHeader">
			Gusti Ngurah Yama Adi Putra's Journey
		</article>
	</div>
	<hr class = "garis">
	{% block content %}
	{% endblock %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript" src="{% static 'js/count.js' %}"></script>
<script src="https://apis.google.com/js/platform.js" async defer></script>
<!-- <script type="text/javascript" src="{% static 'js/datatables.min.js' %}"></script> -->
</body>
</html>

lab_9/templates/book.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
		<center><h1 class = "text" style="margin-left:2vw">My Library</h1></center>
		
		<div style="margin:2vw">
		<h4 class="text" style="margin-bottom: 0vw"> Search Category: </h4>
		<input type="text" name="search" id="sabeb" style="width:35vw">
        <button class="btn btn-sm btn-info" id="buton">Submit</button>

        	{% if user.is_authenticated %}
                <div style="float:right">
                	<h3 class="greet text"> Hello, {{ user.first_name }} {{ user.last_name }}</h3>
                    <a href="{% url 'lab_9:logout' %}" style="color:#e50000; float:right"><h4><strong>Logout</strong></h4></a>
                </div>
            {% else %}
            	<br>
                <a href="{% url 'social:begin' 'google-oauth2' %}" style="color:#0086b3"><h5><strong>Sign in With Google</strong></h5></a>
            {% endif %}  

            {% if messages %}
			  <ul class="messages">
			    {% for message in messages %}
			      <li class="{{ message.tags }}" style="color:#e50000; ">{{ message }}</li>
			    {% endfor %}
			  </ul>
			{% endif %}

			<h4 class = "text" id="counter">Favourite count : {{ message }} </h4>
			<table id="customers" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
				<thead class="thead-dark">
					<tr>
						<th class="th-sm"></th>
						<th class="th-sm">Book Title</th>
						<th class="th-sm">Author</th>
						<!--       
						<th class="th-sm">Publisher
						<i class="fa fa-sort float-right" aria-hidden="true"></i>
						</th> -->
						<th class="th-sm">Date</th>
						<th class="th-sm">Favorite</th>
					</tr>
				</thead>
				<tbody id="boddy">
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td>
						</tr>
				</tbody>
			</table>


		</div>
{% endblock %}